# Fallbacks for local development only
app:
  domain: ${SERVER_DOMAIN:https://servicerized.com}

server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.github.noeeekr: DEBUG

spring:
  datasource:
    driver-class-name: ${POSTGRES_DRIVER:org.postgresql.Driver}
    username: ${POSTGRES_USER:identity}
    password: ${POSTGRES_PASSWORD:identity}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/servicerized}

  thymeleaf:
    prefix: classpath:templates/
  
  mail:
    host: ${MAILER_HOST:servicerized.gmail.com}
    port: 587
    username: ${MAILER_NAME:servicerized@gmail.com}
    password: ${MAILER_PASSWORD:servicerized}
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true

  liquibase:
    enabled: false
  
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.batch_size: 30
      hibernate.jdbc.order_inserts: true
      hibernate.jdbc.order_updates: true
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.use_sql_comments: true # Fixed: was user_sql_comments