<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.github.noeeekr</groupId>
        <artifactId>servicerized</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
	
	<artifactId>product-service</artifactId>
	<name>Servicerized Product Service</name>
	<description>This service provides tools to manage product listings, categories, and inventory.</description>
	<version>1.0.0-SNAPSHOT</version>
	
	<packaging>jar</packaging>
	
	<properties>
    	<main.basedir>${basedir}/../..</main.basedir>
	
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
	</properties>
	
	<dependencies>
        <!-- Data Types -->
        <dependency>
            <groupId>com.github.f4b6a3</groupId>
            <artifactId>uuid-creator</artifactId>
            <version>6.0.0</version>
        </dependency>

        <!-- Internal Communication -->
        <dependency>
            <groupId>com.github.noeeekr</groupId>
            <artifactId>common-response</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

		<!-- Database -->
		<!-- Testing Database -->
		<dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>       

		<!-- Production Database -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

		<!-- Database Pre-configurated Models -->
		<dependency>
			<groupId>com.github.noeeekr</groupId>
			<artifactId>common-repository</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

		<!-- Database Models -->
		<dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>7.0.10.Final</version>
        </dependency>
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
            <version>3.2.0</version>
        </dependency>

        <!-- Database Migration -->
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
            <scope>compile</scope>
        </dependency>

		<!-- Spring Boot Dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		
        <!-- Testing -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

		<!-- Logging -->
		<!-- Hibernate Logging Dependency -->
        <dependency>
            <groupId>org.jboss.logging</groupId>
            <artifactId>jboss-logging</artifactId>
            <version>3.6.1.Final</version>
        </dependency>

        <!-- API -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.noeeekr</groupId>
            <artifactId>common-controller</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <!-- API Security -->
        <dependency>
            <groupId>com.github.noeeekr</groupId>
            <artifactId>common-authorization</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <!-- Helpers -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.34</version>
            <scope>provided</scope>
        </dependency>
	</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
